include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # CONST → ERREURS (non-négociable)
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_constructors_in_immutables: error

    # BuildContext → ERREUR
    use_build_context_synchronously: error

    # Mémoire → ERREURS
    cancel_subscriptions: error
    close_sinks: error

linter:
  rules:
    # --- PERFORMANCE & RENDU ---
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - sort_child_properties_last

    # --- RIGUEUR DU CODE ---
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - always_put_required_named_parameters_first
    - use_super_parameters

    # --- SÉCURITÉ ---
    - use_build_context_synchronously
    - unawaited_futures

    # --- STYLE & PROPRETÉ ---
    - cascade_invocations
    - directives_ordering
    - prefer_final_locals
    - omit_local_variable_types
    - prefer_mixin