// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7eJPG2es3M7pf2jku9UCnp0NklwcyeQ',
    appId: '1:246547675738:web:3a1a8925e780d70dbc7663',
    messagingSenderId: '246547675738',
    projectId: 'reservation-kite',
    authDomain: 'reservation-kite.firebaseapp.com',
    storageBucket: 'reservation-kite.firebasestorage.app',
    measurementId: 'G-QJYYCQQ2TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYBNpFjyyihSVB9X5IgKDyarVGrhOIBHo',
    appId: '1:246547675738:android:a708f0f4811b5bf1bc7663',
    messagingSenderId: '246547675738',
    projectId: 'reservation-kite',
    storageBucket: 'reservation-kite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5Kw1tyx2RAvtSQxjNR83yKxMgCMHIME',
    appId: '1:246547675738:ios:f0b01e20ebf21049bc7663',
    messagingSenderId: '246547675738',
    projectId: 'reservation-kite',
    storageBucket: 'reservation-kite.firebasestorage.app',
    iosBundleId: 'com.example.reservationKite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ5Kw1tyx2RAvtSQxjNR83yKxMgCMHIME',
    appId: '1:246547675738:ios:f0b01e20ebf21049bc7663',
    messagingSenderId: '246547675738',
    projectId: 'reservation-kite',
    storageBucket: 'reservation-kite.firebasestorage.app',
    iosBundleId: 'com.example.reservationKite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7eJPG2es3M7pf2jku9UCnp0NklwcyeQ',
    appId: '1:246547675738:web:e8a96c531b83f16abc7663',
    messagingSenderId: '246547675738',
    projectId: 'reservation-kite',
    authDomain: 'reservation-kite.firebaseapp.com',
    storageBucket: 'reservation-kite.firebasestorage.app',
    measurementId: 'G-XR2GLYNE7R',
  );
}
